### ISSUE TITLE
Is there any way to escape curly brackets?

### ISSUE THREAD

**Issue by rijkvanzanten** [userpixel/micromustache#109]
Heya! For the (very) incidental times where we need to keep a set of brackets in the output string, is there any way to escape `{` characters in the template string?

I was hoping to be able to use an escape character as follows:

```js
const { render } = require("micromustache");

const data = { hello: 'world' };

// Regular usage
const templateA = 'Example: {{hello}}';
const resultA = render(templateA, data);
// => ✅ "Example: world"

// Try to output "Example: {{hello}}"
const templateB = 'Example: \{\{hello\}\}';
const resultB = render(templateB, data);
// => ❌ "Example: world"
```

I can technically get the desired output by inserting brackets in the data object, and then reusing them in the template as follows:

```js
const templateC = 'Example: {{lb}}{{lb}}hello{{rb}}{{rb}}';
const resultC = render(templateC, { ...data, lb: '{', rb: '}' });
// => ✅ "Example: {{hello}}"
```

but that requires the lb/rb combo to be present in the template data. 

I tried injecting the values in the template directly, but that doesn't seem to be supported:

```js
const templateD = 'Example: {{{}}{{{}}hello{{}}}{{}}}';
const resultD = render(templateD, data);
// => ❌ SyntaxError: Unexpected "}}" tag found at position 24

const templateE = 'Example: {{"{"}}{{"{"}}hello{{"}"}}{{"}"}}';
const resultE = render(templateE, data);
// => ❌ "Example: hello"
```

---

As an alternative solution to my use case, is there a way to have micromustache render the original bracket token when an undefined value is passed?

**Comment by alexewerlof** [comment]
This feature unfortunately has performance implications and makes the code more complicated. Meanwhile I have lost the slack I time I had for OSS and can't promise when such a feature may be available. If the use case is really pressing, please use any of the other alternative libs like mustache.js which provide similar features. Sorry.
