### ISSUE TITLE
ie11 support

### ISSUE THREAD

**Issue by viT-1** [userpixel/micromustache#116]
# Current behavior

Trying to render with [umd.min.js](https://cdn.jsdelivr.net/npm/micromustache@8.0.3/dist/micromustache.umd.min.js) as local script
and get TypeError -2146823281 "Object expected"

# Expected behavior
String is rendered.

**Comment by alexewerlof** [comment]
As you know [IE 11 is end of life](https://learn.microsoft.com/en-us/lifecycle/products/internet-explorer-11) and I rather not change the code for the majority of users to support a deprecated browser.

Are you able to replicate the issue in any evergreen browser?
