### ISSUE TITLE
Add migration guide for v6

### ISSUE THREAD

**Issue by userpixel** [userpixel/micromustache#22]

**Comment by tmikaeld** [comment]
I love this library and was just about to pick it up, do you recommend starting with the typescript version directly or go with V5 (current master)?

**Comment by userpixel** [comment]
V 6 is being documented but the api should be solid. You can see the readme
on the typescript branch. Now that it's not released yet but your email
motivated me to finish up soon. Maybe we'll have it by next week.

**Comment by tmikaeld** [comment]
Thanks a lot for the quick reply, it is really appreciated and I love the passion!

Please setup a donation button or something similar, I try to contribute to all open source projects that I use frequently and rely on.

**Comment by userpixel** [comment]
Hi again,
v6 beta is released. Could you do my a favour and give it a try?
You can install it by running `npm i micromustache@beta`.
The documentation is in
https://github.com/userpixel/micromustache/blob/typescript/README.md
The API docs are currently not being updated. Please run these commands to
build it locally:

*git clone git@github.com:userpixel/micromustache.git*
*cd micromustache*
*npm ci*
*npm run docs*
*google-chrome docs/index.html*

Thank you,
+Alex Ewerlöf

**Comment by userpixel** [comment]
@tmikaeld v6 is just released with updated docs and all. Give it a spin and let's head what you think.

**Comment by tmikaeld** [comment]
@userpixel Thanks! It works perfectly, I'll add you to my sponsoring very soon.
