### ISSUE TITLE
Applying function to specific elements from scope, passing custom arguments to renderFn

### ISSUE THREAD

**Issue by fejes713** [userpixel/micromustache#40]
Hey @userpixel, 

Kudos for making an awesome library while focusing on security! I really appreciate it! 🏆 

Are you considering implementing the ability to apply custom functions to just specific elements from the scope? eg. 

Apply truncate function to just 1st and 3rd element and not the 2nd one?

`const template = "My name is {{ truncate name }}, I am {{ age }} old. I come from {{ truncate country }}`.

Also, are you considering adding support for custom arguments to be passed to function? eg. in the mentioned case {{ truncate name 3 }}, so 3 could be passed to the function definition?

Thanks ❤️ and keep up the awesome work!

**Comment by userpixel** [comment]
Hi Stefan,
Thank you. 🙂 This feature is demonstrated in this example:
https://github.com/userpixel/micromustache/blob/master/examples/pipe.js

**Comment by fejes713** [comment]
Thanks for providing me with the example - this already solves us a lot of problems 😄 

With the current implementation of `micromustache`, is it possible to pass custom arguments to pipe functions?

Let's say I have the following code:

```
const pipes = {
  trim(str, length) {
    return str.substring(0, length);
  }
}

const template = "{{name}}'s password is {{password | trim}}!"

function resolveFn(varName, scope) {
  const [vn, ...pipeNames] = varName.split('|')
  const value = get(scope, vn)
  if (pipeNames.length) {
    const fnArr = pipeNames.map(pipeName => pipes[pipeName.trim()])
    return compose(
      fnArr,
      value
    )
  }
  return value
}
```

Would it be possible to pass additional params from the string template? 

eg. "{{name}}'s password is {{password | trim(3)}}!"

**Comment by fejes713** [comment]
I found `custom-get` example. I think that's the right one 😄 Thanks a lot for making this library, for everyone who runs into CSP issues, this is the right fit! ❤️
