### ISSUE TITLE
Can no longer import micromustache v6 using ECMAScript Modules 

### ISSUE THREAD

**Issue by gda-gp** [userpixel/micromustache#47]
Prior to v6, you could use ECMAScript Modules with Node and this package.

For some reason, there isn't the export for render in the current build. I am using this package inside a bigger project and this is the only time I've come across an error with a Node package.

The code I am trying to run:

```javascript
import {render} from 'micromustache';
console.log("Hello, world!");
```

The result when running with `node --es-module-specifier-resolution=node --experimental-modules index.mjs`:

```
import {render} from 'micromustache';
        ^^^^^^
SyntaxError: The requested module 'micromustache' does not provide an export named 'render'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:91:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:106:20)
    at async Loader.import (internal/modules/esm/loader.js:132:24)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! micromustache-demo@1.0.0 start: `node --es-module-specifier-resolution=node --experimental-modules index.mjs`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the micromustache-demo@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Sample repro: https://github.com/gda-gp/micromustache-demo

**Comment by userpixel** [comment]
Could you try `--es-module-specifier-resolution=explicit`?

**Comment by gda-gp** [comment]
@userpixel Still getting the same issue with that flag.

```
> node --es-module-specifier-resolution=explicit --experimental-modules index.mjs

(node:6134) ExperimentalWarning: The ESM module loader is experimental.
file:///Users/user/VendorCode/micromustache-demo/index.mjs:1
import {render} from 'micromustache';
        ^^^^^^
SyntaxError: The requested module 'micromustache' does not provide an export named 'render'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:91:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:106:20)
    at async Loader.import (internal/modules/esm/loader.js:132:24)
```

**Comment by userpixel** [comment]
I verified the bug. Something fishy is going on as the commonjs version of the module works:

```
// import {render} from 'micromustache';
const { render } = require('micromustache');
console.log("Hello, world!", render('Hi {{name}}', {name: 'Alex'}));
```

I also verified that using [esm](https://www.npmjs.com/package/esm) shows the same symptom.

Will make a patch ASAP.

**Comment by gda-gp** [comment]
@userpixel Do you mind releasing a new version on npm? The latest Rollup work fix should fix this.

Thank you!

**Comment by userpixel** [comment]
Have you checked that PR? Can you confirm that it work for you?

**Comment by gda-gp** [comment]
Tried it now, still getting the same error. Confusing since there is a UMD, CJS and ESM build now. I tried switching everything to the ESM build but I'm getting the same error.

**Comment by userpixel** [comment]
There's a test folder in the root that I made specifically for your use
case. Could you see if your runtime has some extra settings that is not
covered by those tests please?

**Comment by userpixel** [comment]
@gda-gp could you verify if it's good now?
