### ISSUE TITLE
Readme error?

### ISSUE THREAD

**Issue by crazy4groovy** [userpixel/micromustache#9]
https://github.com/userpixel/micromustache#example
```
var person = {
  first: 'Michael',
  last: 'Jackson'
};
micromustache.render('Search for {{first}} {{ last }} songs!', person);
// output = "Search Michael Jackson popcorn!"
```

Doesn't `output = "Search for Michael Jackson songs!"` ?

**Comment by userpixel** [comment]
Good spot. Will fix it as soon as I get my hands on a computer. Or are you interested to make a PR.
